### ISSUE TITLE
Problem with UTF-8 filenames in GIT

### ISSUE THREAD

**Issue by webmaster33** [git-for-windows/git#1073]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
Using Git v2.11.1 64 bit under 

```
$ git --version --build-options

git version 2.11.1.windows.1
built from commit: 1c1842bcba45569a84112ec64f72b08eb2d57c68
sizeof-long: 4
machine: x86_64

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [version: 6.1.7601]
Windows 7 64bit.
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: CmdTools
Plink Path: c:\winprg\PuTTY\plink.exe
SSH Option: Plink
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Difftool: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Using Git Extensions 2.49.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

ConEmu (x64), MINGW64

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
"C:\winprg\Git\bin\git.exe" rebase  -i --autosquash --preserve-merges "2e7e7910309fa8952a89be672b7f98cbaa064438"
```
 - What did you expect to occur after running these commands?

Finish the rebase correctly.

### Problem description:
From time to time I notice problems with UTF-8 encoded filenames.
It happens with filenames, which has special accented characters, like:
`ssl/certs/EBG_Elektronik_Sertifika_Hizmet_Sağlayıcısı.pem`

Here is the last message I got when doing a rebase:
```
"C:\winprg\Git\bin\git.exe" rebase --continue
ssl/certs/AC_Raíz_Certicámara_S.A..pem: needs update
ssl/certs/Certinomis_-_Autorité_Racine.pem: needs update
ssl/certs/EBG_Elektronik_Sertifika_Hizmet_Sağlayıcısı.pem: needs update
ssl/certs/NetLock_Arany_=Class_Gold=_Főtanúsítvány.pem: needs update
ssl/certs/TÜBİTAK_UEKAE_Kök_Sertifika_Hizmet_Sağlayıcısı_-_Sürüm_3.pem: needs update
ssl/certs/TÜRKTRUST_Elektronik_Sertifika_Hizmet_Sağlayıcısı_H5.pem: needs update
ssl/certs/TÜRKTRUST_Elektronik_Sertifika_Hizmet_Sağlayıcısı_H6.pem: needs update
You must edit all merge conflicts and then
mark them as resolved using git add
Done

Press Enter or Esc to close console...
```

**Comment by webmaster33** [comment]
Finally I got into a neverending loop, which is caused by UTF-8 format filenames, which seems to be multiple times encoded, and will never match the real UTF-8 filenames:
Further strange issue with the UTF-8 filenames.
Doing an interactive rebase, which halts with errors, and when trying to solve the issue, I get into a loop when continuing the rebase.

Let me show you some interesting steps:
```
-----------------------------------------------------------------
user@PC MINGW64 /w/Dev/!GIT/etckeeper (live_master|REBASE-i 21/32)
$ git status
interactive rebase in progress; onto 2e7e791
Last commands done (21 commands done):
   pick dba4623 fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! Create bash script to clone Moo
   pick 3e96a97 Fix SSL certification files UTF-8 filename problems
  (see more in file .git/rebase-merge/done)
Next commands to do (11 remaining commands):
   pick 2f3dd41 Fix SSL certification files UTF-8 filename problems. Deleted files with UTF-8 problems.
   pick 5081303 fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! Create bash script to cl
  (use "git rebase --edit-todo" to view and edit)
You are currently editing a commit while rebasing branch 'live_master' on '2e7e791'.
  (use "git commit --amend" to amend the current commit)
  (use "git rebase --continue" once you are satisfied with your changes)

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    "ssl/certs/AC_Ra\303\255z_Certic\303\241mara_S.A..pem"
        deleted:    "ssl/certs/Certinomis_-_Autorit\303\251_Racine.pem"
        deleted:    "ssl/certs/EBG_Elektronik_Sertifika_Hizmet_Sa\304\237lay\304\261c\304\261s\304\261.pem"
        deleted:    "ssl/certs/NetLock_Arany_=Class_Gold=_F\305\221tan\303\272s\303\255tv\303\241ny.pem"
        deleted:    "ssl/certs/T\303\234B\304\260TAK_UEKAE_K\303\266k_Sertifika_Hizmet_Sa\304\237lay\304\261c\304\261s\304\2
        deleted:    "ssl/certs/T\303\234RKTRUST_Elektronik_Sertifika_Hizmet_Sa\304\237lay\304\261c\304\261s\304\261_H5.pem"
        deleted:    "ssl/certs/T\303\234RKTRUST_Elektronik_Sertifika_Hizmet_Sa\304\237lay\304\261c\304\261s\304\261_H6.pem"

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        "ssl/certs/AC_Ra\302\241z_Certic\302\240mara_S.A..pem"
        ssl/certs/Certinomis_-_Autorit82_Racine.pem
        "ssl/certs/NetLock_Arany_=Class_Gold=_F8btan\302\243s\302\241tv\302\240ny.pem"

no changes added to commit (use "git add" and/or "git commit -a")
-----------------------------------------------------------------
"C:\winprg\Git\bin\git.exe" rebase --continue
[detached HEAD b0bc4a9] Fix SSL certification files UTF-8 filename problems
 3 files changed, 3 deletions(-)
 delete mode 120000 "ssl/certs/AC_Ra\303\255z_Certic\303\241mara_S.A..pem"
 delete mode 120000 "ssl/certs/Certinomis_-_Autorit\303\251_Racine.pem"
 delete mode 120000 "ssl/certs/NetLock_Arany_=Class_Gold=_F\305\221tan\303\272s\303\255tv\303\241ny.pem"
error: unable to create file ssl/certs/EBG_Elektronik_Sertifika_Hizmet_Sa glay ic is i.pem: Invalid argument
error: unable to create file ssl/certs/T9aB ITAK_UEKAE_K94k_Sertifika_Hizmet_Sa glay ic is i_-_S81r81m_3.pem: Invalid argument
error: unable to create file ssl/certs/T9aRKTRUST_Elektronik_Sertifika_Hizmet_Sa glay ic is i_H5.pem: Invalid argument
error: unable to create file ssl/certs/T9aRKTRUST_Elektronik_Sertifika_Hizmet_Sa glay ic is i_H6.pem: Invalid argument
Could not apply 3e96a97... Fix SSL certification files UTF-8 filename problems
Done

Press Enter or Esc to close console...
-----------------------------------------------------------------
"C:\winprg\Git\bin\git.exe" rebase --continue
error: The following untracked working tree files would be overwritten by merge:
        ssl/certs/AC_Ra!z_Certic mara_S.A..pem
        ssl/certs/Certinomis_-_Autorit82_Racine.pem
        ssl/certs/NetLock_Arany_=Class_Gold=_F8btanLs!tv ny.pem Please move or remove them before you merge.
Aborting
Could not apply 3e96a97... Fix SSL certification files UTF-8 filename problems
Done

Press Enter or Esc to close console...
-----------------------------------------------------------------
user@PC MINGW64 /w/Dev/!GIT/etckeeper (live_master|REBASE-i 31/33)
$ git status
interactive rebase in progress; onto 2e7e791
Last commands done (33 commands done):
   pick 3e96a97 Fix SSL certification files UTF-8 filename problems
   pick 3e96a97 Fix SSL certification files UTF-8 filename problems
  (see more in file .git/rebase-merge/done)
Next commands to do (3 remaining commands):
   pick 3e96a97 Fix SSL certification files UTF-8 filename problems
   pick 2f3dd41 Fix SSL certification files UTF-8 filename problems. Deleted files with UTF-8 problems.
  (use "git rebase --edit-todo" to view and edit)
You are currently editing a commit while rebasing branch 'live_master' on '2e7e791'.
  (use "git commit --amend" to amend the current commit)
  (use "git rebase --continue" once you are satisfied with your changes)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        "ssl/certs/AC_Ra\302\241z_Certic\302\240mara_S.A..pem"
        ssl/certs/Certinomis_-_Autorit82_Racine.pem
        "ssl/certs/NetLock_Arany_=Class_Gold=_F8btan\302\243s\302\241tv\302\240ny.pem"

nothing added to commit but untracked files present (use "git add" to track)

-----------------------------------------------------------------
deleted files:
        "ssl/certs/AC_Ra\302\241z_Certic\302\240mara_S.A..pem"
        ssl/certs/Certinomis_-_Autorit82_Racine.pem
        "ssl/certs/NetLock_Arany_=Class_Gold=_F8btan\302\243s\302\241tv\302\240ny.pem"
-----------------------------------------------------------------
$ git status
interactive rebase in progress; onto 2e7e791
Last commands done (33 commands done):
   pick 3e96a97 Fix SSL certification files UTF-8 filename problems
   pick 3e96a97 Fix SSL certification files UTF-8 filename problems
  (see more in file .git/rebase-merge/done)
Next commands to do (3 remaining commands):
   pick 3e96a97 Fix SSL certification files UTF-8 filename problems
   pick 2f3dd41 Fix SSL certification files UTF-8 filename problems. Deleted files with UTF-8 problems.
  (use "git rebase --edit-todo" to view and edit)
You are currently editing a commit while rebasing branch 'live_master' on '2e7e791'.
  (use "git commit --amend" to amend the current commit)
  (use "git rebase --continue" once you are satisfied with your changes)

nothing to commit, working tree clean
-----------------------------------------------------------------
"C:\winprg\Git\bin\git.exe" rebase --continue
error: unable to create file ssl/certs/EBG_Elektronik_Sertifika_Hizmet_Sa glay ic is i.pem: Invalid argument
error: unable to create file ssl/certs/T9aB ITAK_UEKAE_K94k_Sertifika_Hizmet_Sa glay ic is i_-_S81r81m_3.pem: Invalid argument
error: unable to create file ssl/certs/T9aRKTRUST_Elektronik_Sertifika_Hizmet_Sa glay ic is i_H5.pem: Invalid argument
error: unable to create file ssl/certs/T9aRKTRUST_Elektronik_Sertifika_Hizmet_Sa glay ic is i_H6.pem: Invalid argument
Could not apply 3e96a97... Fix SSL certification files UTF-8 filename problems
Done

Press Enter or Esc to close console...
-----------------------------------------------------------------
$ git status
interactive rebase in progress; onto 2e7e791
Last commands done (34 commands done):
   pick 3e96a97 Fix SSL certification files UTF-8 filename problems
   pick 3e96a97 Fix SSL certification files UTF-8 filename problems
  (see more in file .git/rebase-merge/done)
Next commands to do (3 remaining commands):
   pick 3e96a97 Fix SSL certification files UTF-8 filename problems
   pick 2f3dd41 Fix SSL certification files UTF-8 filename problems. Deleted files with UTF-8 problems.
  (use "git rebase --edit-todo" to view and edit)
You are currently editing a commit while rebasing branch 'live_master' on '2e7e791'.
  (use "git commit --amend" to amend the current commit)
  (use "git rebase --continue" once you are satisfied with your changes)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        "ssl/certs/AC_Ra\302\241z_Certic\302\240mara_S.A..pem"
        ssl/certs/Certinomis_-_Autorit82_Racine.pem
        "ssl/certs/NetLock_Arany_=Class_Gold=_F8btan\302\243s\302\241tv\302\240ny.pem"

nothing added to commit but untracked files present (use "git add" to track)

-----------------------------------------------------------------
deleted files:
        "ssl/certs/AC_Ra\302\241z_Certic\302\240mara_S.A..pem"
        ssl/certs/Certinomis_-_Autorit82_Racine.pem
        "ssl/certs/NetLock_Arany_=Class_Gold=_F8btan\302\243s\302\241tv\302\240ny.pem"
-----------------------------------------------------------------
$ git status
interactive rebase in progress; onto 2e7e791
Last commands done (34 commands done):
   pick 3e96a97 Fix SSL certification files UTF-8 filename problems
   pick 3e96a97 Fix SSL certification files UTF-8 filename problems
  (see more in file .git/rebase-merge/done)
Next commands to do (3 remaining commands):
   pick 3e96a97 Fix SSL certification files UTF-8 filename problems
   pick 2f3dd41 Fix SSL certification files UTF-8 filename problems. Deleted files with UTF-8 problems.
  (use "git rebase --edit-todo" to view and edit)
You are currently editing a commit while rebasing branch 'live_master' on '2e7e791'.
  (use "git commit --amend" to amend the current commit)
  (use "git rebase --continue" once you are satisfied with your changes)

nothing to commit, working tree clean
-----------------------------------------------------------------
"C:\winprg\Git\bin\git.exe" rebase --continue
error: unable to create file ssl/certs/EBG_Elektronik_Sertifika_Hizmet_Sa glay ic is i.pem: Invalid argument
error: unable to create file ssl/certs/T9aB ITAK_UEKAE_K94k_Sertifika_Hizmet_Sa glay ic is i_-_S81r81m_3.pem: Invalid argument
error: unable to create file ssl/certs/T9aRKTRUST_Elektronik_Sertifika_Hizmet_Sa glay ic is i_H5.pem: Invalid argument
error: unable to create file ssl/certs/T9aRKTRUST_Elektronik_Sertifika_Hizmet_Sa glay ic is i_H6.pem: Invalid argument
Could not apply 3e96a97... Fix SSL certification files UTF-8 filename problems
Done

Press Enter or Esc to close console...
-----------------------------------------------------------------
$ git status
interactive rebase in progress; onto 2e7e791
Last commands done (35 commands done):
   pick 3e96a97 Fix SSL certification files UTF-8 filename problems
   pick 3e96a97 Fix SSL certification files UTF-8 filename problems
  (see more in file .git/rebase-merge/done)
Next commands to do (3 remaining commands):
   pick 3e96a97 Fix SSL certification files UTF-8 filename problems
   pick 2f3dd41 Fix SSL certification files UTF-8 filename problems. Deleted files with UTF-8 problems.
  (use "git rebase --edit-todo" to view and edit)
You are currently editing a commit while rebasing branch 'live_master' on '2e7e791'.
  (use "git commit --amend" to amend the current commit)
  (use "git rebase --continue" once you are satisfied with your changes)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        "ssl/certs/AC_Ra\302\241z_Certic\302\240mara_S.A..pem"
        ssl/certs/Certinomis_-_Autorit82_Racine.pem
        "ssl/certs/NetLock_Arany_=Class_Gold=_F8btan\302\243s\302\241tv\302\240ny.pem"

nothing added to commit but untracked files present (use "git add" to track)
-----------------------------------------------------------------
git add .
-----------------------------------------------------------------
$ git status
interactive rebase in progress; onto 2e7e791
Last commands done (35 commands done):
   pick 3e96a97 Fix SSL certification files UTF-8 filename problems
   pick 3e96a97 Fix SSL certification files UTF-8 filename problems
  (see more in file .git/rebase-merge/done)
Next commands to do (3 remaining commands):
   pick 3e96a97 Fix SSL certification files UTF-8 filename problems
   pick 2f3dd41 Fix SSL certification files UTF-8 filename problems. Deleted files with UTF-8 problems.
  (use "git rebase --edit-todo" to view and edit)
You are currently editing a commit while rebasing branch 'live_master' on '2e7e791'.
  (use "git commit --amend" to amend the current commit)
  (use "git rebase --continue" once you are satisfied with your changes)

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        new file:   "ssl/certs/AC_Ra\302\241z_Certic\302\240mara_S.A..pem"
        new file:   ssl/certs/Certinomis_-_Autorit82_Racine.pem
        new file:   "ssl/certs/NetLock_Arany_=Class_Gold=_F8btan\302\243s\302\241tv\302\240ny.pem"

-----------------------------------------------------------------
$ git rebase --continue
[detached HEAD e864e5d] Fix SSL certification files UTF-8 filename problems
 3 files changed, 3 insertions(+)
 create mode 100644 "ssl/certs/AC_Ra\302\241z_Certic\302\240mara_S.A..pem"
 create mode 100644 ssl/certs/Certinomis_-_Autorit82_Racine.pem
 create mode 100644 "ssl/certs/NetLock_Arany_=Class_Gold=_F8btan\302\243s\302\241tv\302\240ny.pem"
error: The following untracked working tree files would be overwritten by merge:
        ssl/certs/AC_Raíz_Certicámara_S.A..pem
        ssl/certs/Certinomis_-_Autorité_Racine.pem
        ssl/certs/NetLock_Arany_=Class_Gold=_Főtanúsítvány.pem
Please move or remove them before you merge.
Aborting
Could not apply 3e96a97... Fix SSL certification files UTF-8 filename problems

-----------------------------------------------------------------
deleted files:
        "ssl/certs/AC_Ra\302\241z_Certic\302\240mara_S.A..pem"
        ssl/certs/Certinomis_-_Autorit82_Racine.pem
        "ssl/certs/NetLock_Arany_=Class_Gold=_F8btan\302\243s\302\241tv\302\240ny.pem"
-----------------------------------------------------------------
$ git status
interactive rebase in progress; onto 2e7e791
Last commands done (36 commands done):
   pick 3e96a97 Fix SSL certification files UTF-8 filename problems
   pick 3e96a97 Fix SSL certification files UTF-8 filename problems
  (see more in file .git/rebase-merge/done)
Next commands to do (3 remaining commands):
   pick 3e96a97 Fix SSL certification files UTF-8 filename problems
   pick 2f3dd41 Fix SSL certification files UTF-8 filename problems. Deleted files with UTF-8 problems.
  (use "git rebase --edit-todo" to view and edit)
You are currently editing a commit while rebasing branch 'live_master' on '2e7e791'.
  (use "git commit --amend" to amend the current commit)
  (use "git rebase --continue" once you are satisfied with your changes)

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    "ssl/certs/AC_Ra\302\241z_Certic\302\240mara_S.A..pem"
        deleted:    ssl/certs/Certinomis_-_Autorit82_Racine.pem
        deleted:    "ssl/certs/NetLock_Arany_=Class_Gold=_F8btan\302\243s\302\241tv\302\240ny.pem"

no changes added to commit (use "git add" and/or "git commit -a")
-----------------------------------------------------------------
$ git checkout -- *
-----------------------------------------------------------------
$ git status
interactive rebase in progress; onto 2e7e791
Last commands done (36 commands done):
   pick 3e96a97 Fix SSL certification files UTF-8 filename problems
   pick 3e96a97 Fix SSL certification files UTF-8 filename problems
  (see more in file .git/rebase-merge/done)
Next commands to do (3 remaining commands):
   pick 3e96a97 Fix SSL certification files UTF-8 filename problems
   pick 2f3dd41 Fix SSL certification files UTF-8 filename problems. Deleted files with UTF-8 problems.
  (use "git rebase --edit-todo" to view and edit)
You are currently editing a commit while rebasing branch 'live_master' on '2e7e791'.
  (use "git commit --amend" to amend the current commit)
  (use "git rebase --continue" once you are satisfied with your changes)

nothing to commit, working tree clean
-----------------------------------------------------------------
$ git rebase --continue
error: The following untracked working tree files would be overwritten by merge:
        ssl/certs/AC_Raíz_Certicámara_S.A..pem
        ssl/certs/Certinomis_-_Autorité_Racine.pem
        ssl/certs/NetLock_Arany_=Class_Gold=_Főtanúsítvány.pem
Please move or remove them before you merge.
Aborting
Could not apply 3e96a97... Fix SSL certification files UTF-8 filename problems

-----------------------------------------------------------------

```

**Comment by sxlijin** [comment]
Can you [clone this repo](https://github.com/sxlijin/utf8-issue) and see if you can rebase the `utf8-file` branch onto `master`?

**Comment by webmaster33** [comment]
I tried your repo and I was able to successfully rebase the utf8 branch.

Could not be possible, that an earlier version of git had utf8 file handling problem, but it was fixed in newer versions? The earlier buggy git might store utf8 filenames in database wrongly, so current version can not decode correctly. 
Just an idea of possible reason of the noticed utf8 problems.

**Comment by sxlijin** [comment]
Is anyone else on the project seeing this issue?

**Comment by thomazpadilha** [comment]
I'm also having the problems with utf-8 encodings.

## Version
First saw it on 2.11.3.windows and updated to 2.12.0.windows.1 and problem persists. I've tested it both on a development machine and on a nearly clean machine as well (with git just installed on it).

## Shell
I've tested with both CMD, PowerShell and Git Bash. It happens the same on both of them.

## Reprodution
To reproduce all I need to do is create a folder, init a repository (git init) and create any file with accents, such as "exceção.txt". When I run git status that's what I get:


Untracked files:
  (use "git add <file>..." to include in what will be committed)

        "exce\303\247\303\243o.txt"


## Further info
If I try to checkout the file with the name it shows on git status I receive the following error:

fatal: pathspec 'exce\303\247\303\243o.txt' did not match any files


If I try to checkout the file with it's actual name (exceção.txt) it works as expected.

One side-effect I've noticed with this is that when I'm working with Visual Studio 2017 whenever a file with accents is modified it can't be undone.

**Comment by thomazpadilha** [comment]
After running the following code (which is mentioned on #1087 ):
`git config core.quotepath off`
The output from git status shows properly:
```
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   exceção.txt
```
However, other commands such as log shows other kind of encoding conflicts (below is an output from git log --inline):
```
3cd9dc3 Inser<C3><A7><C3><A3>o do exce<C3><A7><C3><A3>o.txt
```
The original commit message was "Inserção do exceção.txt".

Visual Studio 2017 still can't undo commits (I believe it's related to the other encoding conflict). Also, I tested the same case on Ubuntu with bash and the output from git status is the same.

**Comment by sxlijin** [comment]
@thomazpadilha I just checked 5 versions of Git and this seems to be the desired behavior going all the way back to pre-Git-2.x.x; I'm not sure why this is the case but I would advise reaching out to the Git mailing list (git@vger.kernel.org) to further discuss this issue, because (1) your issue is clearly distinct from the original issue (which seems to possibly be machine-specific) and (2) it's not G4W-specific, but is relevant to core Git.

**Comment by thomazpadilha** [comment]
@sxlijin I agree with you about it being a part of Git's core, since on Ubuntu it had the same behaviour.

As I've been following #1087 I managed to fix both problems on the windows shells (cmd, powershell and git bash) but still no luck with Visual Studio 2017 (which makes me believe there's still something between git and the IDE which suffers from encoding problems).

Thanks for the reply, I'll keep following the other issue and will try to reach out to the Git mailing list if I manage to have a clearer vision of the problem so I can report it.

**Comment by shiftkey** [comment]
@thomazpadilha 

> still no luck with Visual Studio 2017 (which makes me believe there's still something between git and the IDE which suffers from encoding problems).

Can you provide details of what you're seeing there? Maybe @whoisj can help bring this to the attention of the team, if they're not already aware of it...

**Comment by whoisj** [comment]
@thomazpadilha @shiftkey there are bugs in the RTM version of 2017 related to encoding of strings. Fixes for them are forth coming. 😄

**Comment by thomazpadilha** [comment]
@whoisj I can't tell you how happy I am to hear that!

I'm convincing my team to start new projects on TFS with git instead of TFVC and knowing that it's having such a quick support from Microsoft definitely helps.

Thanks for the info.

**Comment by dscho** [comment]
> Is anyone else on the project seeing this issue?

I am wondering the same...

**Comment by shiftkey** [comment]
@dscho I think we can close this out

**Comment by dscho** [comment]
Thanks, all!
