### ISSUE TITLE
New experimental stash builtin fails with changes in submodule [recipe included]

### ISSUE THREAD

**Issue by t-b** [git-for-windows/git#1820]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.19.0.rc2.windows.1
cpu: x86_64
built from commit: 425f414f8e04123eacb5597776d6a8de445a8d8b
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Disabled
Enable Builtin Rebase: Enabled
Enable Builtin Stash: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nope

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
mkdir test
cd test
git init
echo 1 > file
git add file
git commit file -m "message"
git submodule add ./ mysubmod
git commit -m "Add submodule"
echo 2 > mysubmod/file
git checkout -b mybranch
git rebase -i --autosquash master
```

 - What did you expect to occur after running these commands?

That it works.

 - What actually happened instead?

```
$ rm -rf test/ && ./repro.sh
Initialized empty Git repository in E:/projekte/test/.git/
[master (root-commit) 97c0108] message
 1 file changed, 1 insertion(+)
 create mode 100644 file
Cloning into 'E:/projekte/test/mysubmod'...
done.
[master 282a50f] Add submodule
 2 files changed, 4 insertions(+)
 create mode 100644 .gitmodules
 create mode 160000 mysubmod
Switched to a new branch 'mybranch'
M       mysubmod
fatal: Unexpected stash response: ''
```

**Comment by PhilipOakley** [comment]
Can you also report this, with MVCE, on the git developers list git@vger.kernel.org 
I believe it has already been reported, but having clarification and the MVCE is always a help.

The git@vger.kernel.org list **only** accepts plain text - any HTML part is deemed as indicating spam! The list is open and will cc all contributors

The list archive is at "https://public-inbox.org/git/?q= " with a recent report [here](https://public-inbox.org/git/2659750.rG6xLiZASK@twilight/)

**Comment by t-b** [comment]
@PhilipOakley Sure. Will do. I'm following the git ML as well.

**Comment by dscho** [comment]
@t-b as that thread ended up reverting something that was not even related to the built-in stash, I am now puzzled whether this issue still persists for you?

**Comment by dscho** [comment]
(In particular since your reproducer fails to reproduce the issue with v2.19.0...)

If it is fixed, please close the ticket.

**Comment by dscho** [comment]
Okay, I'll go ahead and assume that the issue was fixed by that partial revert.

**Comment by t-b** [comment]
@dscho Nope, I can still reproduce it with 2.19.1.windows.1.

**Comment by dscho** [comment]
*sigh* I could have done something about that in the past day, *before* v2.19.1 was released.

**Comment by dscho** [comment]
Whoops, forgot to re-open.

**Comment by dscho** [comment]
I think I found the culprit: https://github.com/dscho/git/compare/git-for-windows:master...fix-built-in-rebase-autostash. As stated in the commit message, this lacks a regression test. @t-b how about it? Could you turn your MCVE into a test case, say, for `t/t3426-rebase-submodule.sh`?

**Comment by dscho** [comment]
For lurkers: the patch series [was contributed to the Git mailing list](https://public-inbox.org/git/pull.56.git.gitgitgadget@gmail.com/).
