### ISSUE TITLE
Portable GfW no longer runs from network drive

### ISSUE THREAD

**Issue by cfbrobak** [git-for-windows/git#2036]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
PortableGit-2.20.1-64-bit.7z.exe
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Portable GfW unpacked in directory "H:\DevTools\pgm\Git-2.20.1" by running the .exe file.
H: is a mapped network drive.
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Version 2.18.0 is also installed in the same way (directory "H:\DevTools\pgm\Git-2.18.0") and runs without problems.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell or cmd.exe

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
- Executing "H:\DevTools\pgm\Git-2.20.1\git-bash.exe" does nothing and returns nothing.
- Executing "H:\DevTools\pgm\Git-2.20.1\cmd\git.exe" returns "Invalid executable path:".
```

**Comment by PhilipOakley** [comment]
This sounds like a symptom of another 'corner case' problem that's recently been reported for some files on network devices (#1989), Maybe.

**Comment by dscho** [comment]
> This sounds like a symptom of another 'corner case' problem that's recently been reported for some files on network devices (#1989), Maybe.

I am not quite sure that it is the same issue. It sounds more related to recent changes in `git-wrapper.c`...

**Comment by dscho** [comment]
A new [snapshot](https://wingit.blob.core.windows.net/files/index.html) is available that should fix this issue. Could I ask y'all to please test?

**Comment by cfbrobak** [comment]
I just tried this snapshot: PortableGit-prerelease-2.20.1.windows.1.27.g9f16cdd421-64-bit.7z.exe
Unfortunately, the problem still seems to be there.

**Comment by dscho** [comment]
@cfbrobak thanks for testing. However, I just unpacked that portable Git into `D:\test-git\portable-2.20.1-cmd-fix` and then ran this:

```powershell
PS C:\Users\me> & '\\localhost\d$\test-git\portable-2.20.1-cmd-fix\cmd\git.exe' version
git version 2.20.1.windows.1.27.g9f16cdd421
```

So it works here. If it fails on your side, could you try the same as I did? And if that works, provide a bit more detail what else you did? Like, details about your particular setup, e.g. is this a Samba drive or something more obscure?

**Comment by dscho** [comment]
Sorry, I just tried on a network drive that is on a different continent, and it still worked:

```powershell
PS C:\Users\me> \\us-east2\users\me\portable-20190129\cmd\git version
git version 2.20.1.windows.1.27.g9f16cdd421
```

The same happens when I map a Samba directory from an Ubuntu VM:

```powershell
PS C:\Users\me> Z:\portable-20190129\cmd\git version
git version 2.20.1.windows.1.27.g9f16cdd421
```

This all makes me think that it is actually very important to know more about your setup, or maybe there is a chance that you can run some custom-built code in a debugger? You would have to install [Git for Windows' SDK](https://gitforwindows.org/#download-sdk) for that. Alternatively, I would need to have interactive access to the setup (we could Live Share so you can verify that I do not do anything untoward with your system). If none of that is an option, there is unfortunately nothing I can do to help.

**Comment by cfbrobak** [comment]
Unfortunately, I am unable to do any of the things that you suggest, the reason being that this is a computer at my job.
What I did do was to install a number of previous Portable GfW versions. It turns out the problem was introduced after version 2.19.2, that is, version 2.19.2 works and 2.20.0 does not work. I don't know if that is of any help.
Anyway, thanks for looking into this issue.

**Comment by dscho** [comment]
Sorry, those are too many obstacles for me to help.

**Comment by natescham** [comment]
-- tst
