### ISSUE TITLE
Git failed to build due to fatal error LNK1181: cannot open input file 'libcurl.lib' with MSVC on windows

### ISSUE THREAD

**Issue by spacelg** [git-for-windows/git#2195]
Setup
•Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
 64-bit
 $ git --version --build-options
 git version 2.9.2.windows.1
 sizeof-long: 4
•Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
 Windows Server 2016 64-bit + VS2017 15.7.2
 $ cmd.exe /c ver
 Microsoft Windows [Version 10.0.17134]

Repro steps:
 1.git clone https://github.com/git-for-windows/git.git D:\git\src
 2.git checkout vs/master
 3.devenv /upgrade git.sln
 4.nuget.exe restore git.sln
 5.msbuild /m /p:Configuration=Release;Platform=x64 /p:WindowsTargetPlatformVersion=10.0.17134.0 /t:Rebuild git.sln

[log_x64_build.log](https://github.com/git-for-windows/git/files/3181278/log_x64_build.log)

Build Git latest revision on master with 2017 failed with the following errors:
LINK : fatal error LNK1181: cannot open input file 'libcurl.lib' [D:\Git\src\git-http-push\git-http-push.vcxproj]
D:\Git\src\git\LinkOrCopyBuiltins.targets(126,5): error MSB3030: Could not copy the file "..\\git-remote-http.exe" because it was not found. [D:\Git\src\git\git.vcxproj]
     2>Done Building Project "D:\Git\src\git\git.vcxproj" (Rebuild target(s)) -- FAILED.
     1>Done Building Project "D:\Git\src\git.sln" (Rebuild target(s)) -- FAILED.

**Comment by dscho** [comment]
> 1.git clone https://github.com/git-for-windows/git.git D:\git\src
> 2.git checkout vs/master

Did you `d:` and then `cd \git\src` between those?

> nuget.exe restore git.sln

Are you following outdated instructions? This should not be necessary anymore.



> D:\Git\src\git\LinkOrCopyBuiltins.targets(126,5): error MSB3030: Could not copy the file "..\git-remote-http.exe" because it was not found. [D:\Git\src\git\git.vcxproj]

Hmm. That path (`D:\Git\src\git\LinkOrCopyBuiltins.targets`) is suspicious. But the full log you included makes more sense. In particular, these lines report that your curl was built correctly:

```
         Building package curl[core,ssl,winssl]:x64-windows... done
         Installing package curl[core,ssl,winssl]:x64-windows...
         Installing package curl[core,ssl,winssl]:x64-windows... done
```

Can you see whether you find `libcurl.lib` somewhere in `D:/Git/src/compat/vcbuild/vcpkg/packages/curl_x64-windows/` or its subdirectories?

**Comment by dscho** [comment]
Aha! A recent `vcpkg` update renamed `libcurl.lib` to `libcurl_imp.lib`.

**Comment by spacelg** [comment]
Hi

Thanks for your reply!

We tried to apply a patch as the code you prodived in fixup! msvc: support building Git using MS Visual C++ . And re-build, it still failed to fatal error LNK1181: cannot open input file 'libcurl.lib'. Looks like it doesn't work. 

Thanks
Lin

**Comment by dscho** [comment]
> Looks like it doesn't work.

That's because you want to use the `vs/master` branch, which has a generated commit on top of `master`. Without it, only `make MSVC=1` is fixed. With it (i.e. today's `vs/master` because I merged the branch with the `fixup!`), your build inside Visual Studio should work, too.

**Comment by spacelg** [comment]
Hi,

Thanks for your reply!

Today we use latest vs/matest commit 9931b2e. This issue still exits and not fixed.

[log_x64_build.log](https://github.com/git-for-windows/git/files/3211003/log_x64_build.log)

Errors:
LINK : fatal error LNK1181: cannot open input file 'libcurl.lib' [D:\Git\src\git-imap-send\git-imap-send.vcxproj]
D:\Git\src\git\LinkOrCopyBuiltins.targets(126,5): error MSB3030: Could not copy the file "..\\git-remote-http.exe" because it was not found. [D:\Git\src\git\git.vcxproj]

Could you please look at this again? And re-open this issue.

Thanks,
Lin

**Comment by dscho** [comment]
I reopened this issue, but I do not feel okay with all work being dumped on me. Please do investigate as much as you can, too.
