### ISSUE TITLE
Invalid signature for package databases

### ISSUE THREAD

**Issue by magneticflux-** [git-for-windows/git#2521]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

Not in the `git` client. Reproducible via curl, wget, or a web browser.

Download these files:
 - https://wingit.blob.core.windows.net/x86-64/git-for-windows.db
 - https://wingit.blob.core.windows.net/x86-64/git-for-windows.db.sig

Use a PGP client to verify the signature of the file.

### Details

The signatures used to sign the packages are invalid.

Raw GPG Audit Log:
```console
$ gpg --verify git-for-windows.db.sig git-for-windows.db
gpg: Signature made 02/16/20 15:01:56 Central Standard Time
gpg:                using RSA key 57759F748D223F034D8BE870BB3AA74136C569BB
gpg: BAD signature from "Johannes Schindelin <johannes.schindelin@gmx.de>" [full]
```

My PGP client's output:

![image](https://user-images.githubusercontent.com/9124288/74901041-38543100-5367-11ea-85ed-dcd9a7158377.png)

**Comment by dscho** [comment]
Yep, I see it. Investigating.

**Comment by dscho** [comment]
Fixed (manually).

Explanation: I moved the release engineering to a new Azure Build/Release Pipeline combo, and while splitting up the build part from the release part, I failed to realize that the release part (which uploads the Pacman packages) needs to sign the updated package databases.

**Comment by rimrul** [comment]
You've updated the package databases, but the packages (namely `mingw-w64-i686-git` and `mingw-w64-i686-git-doc-html` are still missing signatures, according to pacman.

**Comment by dscho** [comment]
Try again, I _just_ fixed that.

**Comment by dscho** [comment]
Hold on, @elieux just pointed out that the databases need to be updated, too.

**Comment by dscho** [comment]
Okay, that was stressful. I uploaded the updates databases, and it works over here.

Can anyone else confirm?

**Comment by rimrul** [comment]
Yes, it's working again.

**Comment by rimrul** [comment]
Yes, it's working again.

**Comment by dscho** [comment]
Thank you for testing!
