### ISSUE TITLE
git bash loses / mangles order of keyboard input received while busy

### ISSUE THREAD

**Issue by kevinushey** [git-for-windows/git#5632]
This one feels hard to reproduce, but I can reproduce somewhat frequently in this scenario. (It may take a few times to get it to work.)

1. Use <kbd>Ctrl + C</kbd> to send an interrupt,
2. While the interrupt is being processed and the prompt is being redrawn, try typing something, e.g. `git`.

I frequently get keyboard input reordered in an unexpected way, e.g.

```
kevin@GGCOMP MINGW64 ~
$ ^C
gi
kevin@GGCOMP MINGW64 ~
$ tgi
```

Note that the `t` keypress was received after `gi` was processed and printed, but while the prompt was being redrawn. The inserted `t` was then placed at the front of the command, instead of the end.

```
kevin@GGCOMP MINGW64 ~
$ git --version
git version 2.49.0.windows.1
```

**Comment by kevinushey** [comment]
You can also reproduce a similar behavior if you type while a longer-running command is executing; e.g. just typing after running `git` and while the usage output is being printed.

**Comment by dscho** [comment]
I experience this in MinTTY all the time. If only I had enough time to copy/edit one of the AutoHotKey-based tests in https://github.com/git-for-windows/msys2-runtime/tree/HEAD/ui-tests to get a reliable reproducer. Maybe one of you gentle people in this here ticket could help out?

**Comment by dscho** [comment]
@kevinushey @KalleOlaviNiemitalo if you have anything in the way of reliable producers, please do download the `install` artifact of https://github.com/git-for-windows/msys2-runtime/actions/runs/22453924078?pr=124, overwrite your `msys-2.0.dll` with the extracted version from that artifact (after backing up the original version!), and run your reproducer. I'm _very_ interested in confirmation or rejection of this fix.

**Comment by KalleOlaviNiemitalo** [comment]
I don't have a repro but I have seen another symptom that may be related.  Sometimes, when I type ahead and press Enter during a Git command in PowerShell Core in Windows Terminal, and the Git command then finishes and the PowerShell prompt returns, the Enter keypress is replaced with a plain `m` at the end of the line.

**Comment by dscho** [comment]
> I don't have a repro but I have seen another symptom that may be related. Sometimes, when I type ahead and press Enter during a Git command in PowerShell Core in Windows Terminal, and the Git command then finishes and the PowerShell prompt returns, the Enter keypress is replaced with a plain `m` at the end of the line.

Well it is possible that this is exactly the same bug that produces a different symptom, too. So: please test?

**Comment by j4-c4** [comment]
@dscho I've tried a few things with the dll that haven't been working for a while:

- running git diff, pressing `q<enter>` to exit it while it's still loading and then typing another command
- opening a new terminal and entering a few commands while it's still loading

They work perfectly.

There is one thing that hasn't worked for months and still isn't - [RepoZ's CLI](https://github.com/awaescher/RepoZ). Typing `grr cd :6` does nothing and leaves a `^M` behind my cursor once the prompt reappears.

I believe `grr` used to function by putting `cd /path/to/repo` in my terminal input and then pressing enter - all as if I'd entered it myself. It was a bit hacky and obviously prevented you typing ahead given that it essentially commandeered your terminal for a bit, but it was a useful program. 

Still, I'm used to doing without it at this point. Not having to deal with mangled input is a massive win.

**Comment by dscho** [comment]
@j4-c4 thank you for testing!

The `^M` thing might be indicative of some flawed CR/LF handling, and looks like a totally different issue. Let's push this here bug fix over the finish line first.

**Comment by kevinushey** [comment]
I can confirm this fixes the issue for me too -- tested with

```
$ git --version
git version 2.53.0.windows.1
```

with the build of `msys-2.0.dll` copied into the `/usr/bin` directory of my Git for Windows installation.

**Comment by kevinushey** [comment]
For posterity, here's what I see in the Git for Windows shell:

```
kevin@GGCOMP MINGW64 ~
$ ^C
gi
kevin@GGCOMP MINGW64 ~
$ git
```

which is what I hoped to see. Thanks!

**Comment by dscho** [comment]
@kevinushey thank you for testing! I am glad that one week of analysing and investigating and fixing paid off.

**Comment by kevinushey** [comment]
It is hugely appreciated! This is one of those issues that slowly drives you crazy over time. 🙂 I'm certain it wasn't easy to nail down -- thank you!

**Comment by j4-c4** [comment]
@dscho It seems I spoke too soon, I'm still seeing this. It feels like it's less often but that could be placebo. I should've mentioned this previously, but I'm using Windows Terminal, so I'm not entirely sure if this fix applies to it at all.

**Comment by dscho** [comment]
@j4-c4 I also should have updated this ticket: The proposed patches introduced a serious regression, and I have not been able so far to come up with a new iteration of the patch series that addressed the out-of-order keystrokes _without_ that regression.

I'm curious, though, if you can find ways to reproduce your issues reliably? I am interested in anything that can be converted into an AutoHotKey-based test like [this one](https://github.com/dscho/msys2-runtime/blob/fix-jumbled-character-order/ui-tests/keystroke-order.ahk).

**Comment by dscho** [comment]
@KalleOlaviNiemitalo @kevinushey @j4-c4 good news! There is now an updated patch series which should address the remaining out-of-order issues, once and for all. Would you please download the `install` artifact from [this build](https://github.com/git-for-windows/msys2-runtime/actions/runs/23655304127?pr=124#artifacts), extract the `msys-2.0.dll` from there and (temporarily) replace the one in your installation, then test thoroughly?

**Comment by dscho** [comment]
/add relnote bug In some circumstances, when typing while a still-running program is about to terminate, [the typed characters could arrive out of order in Git Bash](https://github.com/git-for-windows/git/issues/5632). This bug [was fixed](https://github.com/git-for-windows/msys2-runtime/pull/124).

The workflow run [was started](https://github.com/git-for-windows/build-extra/actions/runs/23709490712)

**Comment by j4-c4** [comment]
@dscho I grabbed the dll you posted on Friday and have tried it at work today. Sadly, I'm still seeing the issue. No reliable reproduction either, unfortunately - though I'd guess it happens more often towards the end of the day when a lot more programs have been started (and therefore resources are more limited). If you're working off a laptop, unplugging it + turning on battery saver also seems to help make it happen more often.

**Comment by dscho** [comment]
> I grabbed the dll you posted on Friday and have tried it at work today. Sadly, I'm still seeing the issue. No reliable reproduction either, unfortunately - though I'd guess it happens more often towards the end of the day when a lot more programs have been started (and therefore resources are more limited). If you're working off a laptop, unplugging it + turning on battery saver also seems to help make it happen more often.

Thank you @j4-c4. There have been a couple of last-minute fixes. Could you grab the one from https://github.com/git-for-windows/git-sdk-64/blob/HEAD/usr/bin/msys-2.0.dll (it was deployed to Git for Windows' SDK 13h ago, and this is slated to become the version that will make it into the next Git for Windows version).

I'm curious as to _any_ breadcrumb you could leave here regarding the remaining issues you're seeing? Even if you can only vaguely describe the issues, it would probably make sense to leave a description here, just in case other people see similar things and might be able to add more pieces to the puzzle.

**Comment by j4-c4** [comment]
I've grabbed the dll (from mingit-x86_64, hopefully the correct place) and will let you know if I see it again.

The issue I see is when typing something like `git checkout main` while waiting on the prompt to return from a previous command, a character will be shifted to the start. The input I see could be `cgit chekout main` or ` git checkoutmain` (space at the start). It seems more likely to happen under resource constrained conditions, when the time between commands is longer.

**Comment by dscho** [comment]
> The issue I see is when typing something like `git checkout main` while waiting on the prompt to return from a previous command, a character will be shifted to the start. The input I see could be `cgit chekout main` or ` git checkoutmain` (space at the start). It seems more likely to happen under resource constrained conditions, when the time between commands is longer.

That matches pretty precisely the symptoms I emulate in those UI tests, and that were supposedly addressed by those fixes...

> I've grabbed the dll (from mingit-x86_64, hopefully the correct place) and will let you know if I see it again.

Well, now there is [a new snapshot](https://gitforwindows.org/git-snapshots/#2026-03-31T11:20:45.000Z) with that new MSYS2 runtime. Remember, snapshots are designed to be as close to "continuous releases" as I can make them, they are even code-signed. So, in theory, you should be able to update to that snapshot and everything (including the keystroke order) should work fine.

**Comment by kevinushey** [comment]
Sorry for the delay. Chiming in to say I tested with the latest snapshot built today, and the issue appears to be entirely resolved for me. Thanks again!

```
kevin@GGCOMP MINGW64 ~
$ git --version
git version 2.53.0.windows.2.8.gf549d3f011.20260331112157
```

**Comment by j4-c4** [comment]
Still seeing it. Wasn't sure whether it was really happening or if I was mistyping (`git` -> `tig` is innocuous enough) but I did get some bad ones today. Greatly assisted by my laptop being very slow.

I recorded my terminal + keyboard out of an abundance of paranoia and got a few clips of it happening.

https://github.com/user-attachments/assets/17f1522a-7f57-4078-8b11-f9945db80589

https://github.com/user-attachments/assets/257b091b-82f1-4b1b-afc3-a1ee0aa17760

https://github.com/user-attachments/assets/d4591188-003e-433b-93ac-ca67cd8e87ff

Also note that the cursor flicks back to the start of the line when typing in the first 10~20 columns. It's most clearly visible in the third video. That doesn't happen outside the snapshot build.

As a possible reproduction, I also noticed text _completely disappearing_ when I run `git diff` when I had a one-line change in the working directory, meaning that it wouldn't open the pager. Typing `git checkout main` (without pressing enter) before `git diff` returned might lead to only having `ain` appearing in the text area. This seems like a separate issue though (something to do with the pager?), given that it eats the characters instead of rearranging them. This `git diff` consuming behaviour happens both on the snapshot and `2.53.0.2`, so there's no regression at least.

**Comment by dscho** [comment]
@j4-c4 for the record, I also saw this yesterday. My machine was under _heavy_ load, and I did a _long_ typeahead, and a large chunk that should have been at the end was now in the middle.

My suspicion is that there is still a tiny time window in which the input transfer between MSYS and native consumer is too late as the input has been partially consumed, or something like that. At this point, I am seeing this _very_ rarely, though (I've been running with this fix for weeks now and yesterday was the first time it hit me, and I was putting a _lot_ of load on my machine). Meaning: At this point, I think we crossed the threshold of diminishing returns, and I cannot really justify pouring more time into it.

_Maybe_ one of @tyan0's additional fixes (he was _really_ busy and produced some patches that I am _seriously_ happy about) will alleviate this issue; IIUC Cygwin v3.6.8 is imminent and we'll find out as soon as it trickled down to Git for Windows (and by "trickle down" I mean, of course, "I will work as hard as always to rebase MSYS2's and Git for Windows' patches on top, verify that everything works as expected, and then deploy it to Git for Windows' SDK").
