### ISSUE TITLE
Installing git sdk 1.0.1 results in a http proxy error

### ISSUE THREAD

**Issue by paladox** [git-for-windows/git#630]
**Steps to reproduce**

* Download the git sdk from https://github.com/git-for-windows/build-extra/releases/tag/git-sdk-1.0.1 I am using the 64bit one.

* Then run it to start the installation process.

**Actual results**

* I get this error

:: Synchronizing package databases...
 git-for-windows                               2004.0   B   280K/s 00:00 [#######################################] 100%
 mingw32                                        231.4 KiB   421K/s 00:01 [#######################################] 100%
 mingw32.sig                                     96.0   B  0.00B/s 00:00 [#######################################] 100%
      1 [main] pacman 10184 C:\git-sdk-64\usr\bin\pacman.exe: *** fatal error in forked process - fork: can't reserve memory for parent stack 0x600000 - 0x800000, (child has 0x400000 - 0x600000), Win32 error 487
   1451 [main] pacman 10184 cygwin_exception::open_stackdumpfile: Dumping stack trace to pacman.exe.stackdump
      1 [main] pacman 7544 fork: child -1 - forked process 10184 died unexpectedly, retry 0, exit code 0x100, errno 11
error: GPGME error: Invalid crypto engine
error: failed to update mingw32 (invalid or corrupted database (PGP signature))
 mingw64                                        230.4 KiB   567K/s 00:00 [#######################################] 100%
 mingw64.sig                                     96.0   B  93.8K/s 00:00 [#######################################] 100%
error: GPGME error: Invalid crypto engine
error: failed to update mingw64 (invalid or corrupted database (PGP signature))
 msys                                           129.4 KiB   428K/s 00:00 [#######################################] 100%
 msys.sig                                        96.0   B  93.8K/s 00:00 [#######################################] 100%
error: GPGME error: Invalid crypto engine
error: failed to update msys (invalid or corrupted database (PGP signature))
error: database 'mingw32' is not valid (invalid or corrupted database (PGP signature))
error: database 'mingw64' is not valid (invalid or corrupted database (PGP signature))
error: database 'msys' is not valid (invalid or corrupted database (PGP signature))

There was a problem accessing the MSys2 repositories
If your setup requires an HTTP proxy to access the web,
please specify it here, otherwise leave it empty.

**Expected results**

* It should correctly connect and download what ever it needs to download to install. I am not sure what the expected results are since this is my first time installing it because I would like to try and build git.

**Comment by paladox** [comment]
Could it be related to this being fixed in https://github.com/git-for-windows/build-extra/commit/918a119f993fe5d43638e11efd1f5897cc891bfc but never release as an update.

Could we release 1.0.2 or 1.2.0 of the sdk since there were a lot of fixes since august please.

**Comment by dscho** [comment]
I agree that a new SDK installer version is due, but unfortunately it is really poor timing, as I have to work on a different bug (and even more sadly, I have to spend time on reminding bug reporters of the rules in this project, which takes time away from addressing said bug).

**Comment by paladox** [comment]
Thanks.

**Comment by dscho** [comment]
@paladox do not thank me in words. Note that it would have made my life substantially easier if somebody like you would have worked on fixing the release script. I do not scale well.

**Comment by paladox** [comment]
@dscho sorry I did not try fixing this bug. Its that I doint know how to programme in windows code. It is much easisar in php.

**Comment by dscho** [comment]
If you take a careful look at the branch I merged in https://github.com/git-for-windows/build-extra/compare/c58e4fa2cea28f2606e0ca1472f429efe2d8bc5f%5E...c58e4fa2cea28f2606e0ca1472f429efe2d8bc5f%5E2 you will find that nothing of that is Windows code. It does not even touch any Windows code. It is far away from any Windows code.

And yes, it's not PHP, but it's not like PHP is this unicorn language that is *sooooo* different from shell scripts.

Don't get me wrong, it is nice to see that your name pops up more than once in these tickets. It just feels as if I always end up doing the main chunk of the work, even if you are obviously smart enough to take more of the load.

**Comment by CHK16** [comment]
Hello, @dscho  I still have the same issue. I don't understand how to fix it.

**Comment by dscho** [comment]
@CHK16 are you sure you use 1.0.2?
